[package]
name = "terminal-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
terminal = { path = "../terminal"}

serde = { version = "1.0.202", features = ["serde_derive"] }
serde_json = "1.0.117"